### ISSUE TITLE
Add AKS-Engine-Windows-ContainerD test pass to testgrid

### ISSUE THREAD

**Issue by PatrickLang** [Azure/aks-engine#2830]
Once #1322 is merged and #2829 is done, it's time to add a test pass for the master branch of Kubernetes.

Steps required:

- [ ] Release a version of AKS-Engine with #1322 included
- [ ] Check in new AKS-Engine config at https://github.com/kubernetes-sigs/windows-testing/tree/master/job-templates
- [ ] Add prow config for Windows + ContainerD with AKS-Engine at https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/sig-windows
- [ ] Update the AKS-Engine config after #2827 is resolved
- [ ] Update the AKS-Engine config after #2828 is resolved

**Comment by jsturtevant** [comment]
Testgrid now has green passes for containerd:

https://testgrid.k8s.io/sig-windows-containerd#aks-engine-azure-windows-master-containerd
https://testgrid.k8s.io/sig-windows-containerd#aks-engine-azure-windows-master-containerd-serial-slow
